# Lab API keys setup — Hugging Face + Supabase
#
# Run from repo root or portfolio-mentor-platform:
#   .\scripts\setup-lab-env.ps1
#
# Creates or updates .env.local (never committed to git).

$ErrorActionPreference = "Stop"
$Root = Split-Path -Parent $PSScriptRoot
$EnvFile = Join-Path $Root ".env.local"
$ExampleFile = Join-Path $Root ".env.example"

Write-Host ""
Write-Host "=== Portfolio Lab — API key setup ===" -ForegroundColor Cyan
Write-Host ""

# Step 1 — Hugging Face
Write-Host "STEP 1: Hugging Face Inference token" -ForegroundColor Yellow
Write-Host "  1. Sign up / log in at https://huggingface.co"
Write-Host "  2. Confirm your email (required before creating tokens)"
Write-Host "  3. Open https://huggingface.co/settings/tokens"
Write-Host "  4. New token -> Fine-grained"
Write-Host "  5. Enable: Make calls to Inference Providers"
Write-Host "  6. Copy the token (starts with hf_) — shown only once"
Write-Host ""

$openHf = Read-Host "Open Hugging Face token page in browser now? [Y/n]"
if ($openHf -ne "n" -and $openHf -ne "N") {
    Start-Process "https://huggingface.co/settings/tokens/new?tokenType=fineGrained"
}

$hfToken = Read-Host "Paste HF_TOKEN (or press Enter to skip)"
if ($hfToken -and -not $hfToken.StartsWith("hf_")) {
    Write-Host "Warning: HF tokens usually start with hf_" -ForegroundColor DarkYellow
}

# Step 2 — Supabase (optional)
Write-Host ""
Write-Host "STEP 2: Supabase (optional — shareable proof links)" -ForegroundColor Yellow
Write-Host "  1. Create project at https://supabase.com"
Write-Host "  2. SQL Editor -> run supabase/schema.sql from this repo"
Write-Host "  3. Settings -> API -> copy Project URL + service_role key"
Write-Host ""

$supabaseUrl = Read-Host "SUPABASE_URL (Enter to skip)"
$supabaseKey = ""
if ($supabaseUrl) {
    $supabaseKey = Read-Host "SUPABASE_SERVICE_ROLE_KEY"
}

# Load existing .env.local or .env.example as base
$lines = @{}
if (Test-Path $EnvFile) {
    Write-Host "Updating existing .env.local" -ForegroundColor Green
    Get-Content $EnvFile | ForEach-Object {
        if ($_ -match '^\s*([^#=]+)=(.*)$') {
            $lines[$Matches[1].Trim()] = $Matches[2]
        }
    }
} elseif (Test-Path $ExampleFile) {
    Write-Host "Creating .env.local from .env.example" -ForegroundColor Green
    Get-Content $ExampleFile | ForEach-Object {
        if ($_ -match '^\s*([^#=]+)=(.*)$') {
            $lines[$Matches[1].Trim()] = $Matches[2]
        }
    }
}

function Set-EnvLine($key, $value) {
    if ($value) { $lines[$key] = $value }
}

if ($hfToken) {
    Set-EnvLine "HF_TOKEN" $hfToken
    Set-EnvLine "HF_SUMMARY_MODEL" "facebook/bart-large-cnn"
    Set-EnvLine "HF_EMBED_MODEL" "sentence-transformers/all-MiniLM-L6-v2"
}

if ($supabaseUrl) {
    Set-EnvLine "SUPABASE_URL" $supabaseUrl
    Set-EnvLine "NEXT_PUBLIC_SUPABASE_URL" $supabaseUrl
}
if ($supabaseKey) {
    Set-EnvLine "SUPABASE_SERVICE_ROLE_KEY" $supabaseKey
}

if (-not $lines["NEXT_PUBLIC_APP_URL"]) {
    Set-EnvLine "NEXT_PUBLIC_APP_URL" "http://localhost:3200"
}

# Preserve key order from example where possible
$order = @(
    "OPENAI_API_KEY", "OPENAI_MODEL", "OPENAI_TTS_MODEL", "OPENAI_TTS_VOICE",
    "RESEND_API_KEY", "CONTACT_TO_EMAIL", "CONTACT_FROM_EMAIL",
    "HF_TOKEN", "HF_SUMMARY_MODEL", "HF_EMBED_MODEL",
    "SUPABASE_URL", "SUPABASE_SERVICE_ROLE_KEY", "NEXT_PUBLIC_SUPABASE_URL",
    "NEXT_PUBLIC_APP_URL",
    "NEXT_PUBLIC_DEMO_P01_URL", "NEXT_PUBLIC_DEMO_P02_URL", "NEXT_PUBLIC_DEMO_P03_URL"
)

$written = New-Object System.Collections.Generic.HashSet[string]
$out = @()
foreach ($k in $order) {
    if ($lines.ContainsKey($k)) {
        $out += "$k=$($lines[$k])"
        [void]$written.Add($k)
    }
}
foreach ($k in ($lines.Keys | Sort-Object)) {
    if (-not $written.Contains($k)) {
        $out += "$k=$($lines[$k])"
    }
}

$header = @(
    "# Generated by scripts/setup-lab-env.ps1 — do not commit",
    ""
)
($header + $out) | Set-Content -Path $EnvFile -Encoding utf8

Write-Host ""
Write-Host "Saved: $EnvFile" -ForegroundColor Green
Write-Host ""
Write-Host "Next steps:" -ForegroundColor Cyan
Write-Host "  1. npm run dev   (in portfolio-mentor-platform)"
Write-Host "  2. Open http://localhost:3200/lab/setup"
Write-Host "  3. Click Re-check connection"
Write-Host ""
